"""add_lead_source_channel

Revision ID: add_lead_source_channel
Revises:
Create Date: 2026-04-17

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_lead_source_channel"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("leads", sa.Column("source_channel_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_leads_source_channel_id_channels",
        "leads",
        "channels",
        ["source_channel_id"],
        ["id"],
    )
    op.create_index("idx_leads_source_channel_id", "leads", ["source_channel_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_leads_source_channel_id", table_name="leads")
    op.drop_constraint(
        "fk_leads_source_channel_id_channels", "leads", type_="foreignkey"
    )
    op.drop_column("leads", "source_channel_id")
    # ### end Alembic commands ###
