"""create customer channel links table

Revision ID: create_customer_channel_links
Revises: product_installations_001
Create Date: 2026-04-17 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "create_customer_channel_links"
down_revision = "product_installations_001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_channel_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("discount_rate", sa.DECIMAL(precision=5, scale=4), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["terminal_customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_channel_links_customer_id"),
        "customer_channel_links",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_channel_links_id"),
        "customer_channel_links",
        ["id"],
        unique=False,
    )

    # Create partial unique index for active primary channels
    op.create_index(
        "uq_customer_active_primary_channel",
        "customer_channel_links",
        ["customer_id"],
        postgresql_where=sa.text("role = '主渠道' AND end_date IS NULL"),
        unique=True,
    )

    # 回填存量数据：把现有 customer.channel_id 迁移到 link 表
    op.execute(
        """
        INSERT INTO customer_channel_links (customer_id, channel_id, role, start_date, end_date)
        SELECT id, channel_id, '主渠道', CURRENT_DATE, NULL
        FROM terminal_customers
        WHERE channel_id IS NOT NULL
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_customer_active_primary_channel", table_name="customer_channel_links"
    )
    op.drop_index(
        op.f("ix_customer_channel_links_id"), table_name="customer_channel_links"
    )
    op.drop_index(
        op.f("ix_customer_channel_links_customer_id"),
        table_name="customer_channel_links",
    )
    op.drop_table("customer_channel_links")
    # ### end Alembic commands ###
